### ISSUE TITLE
"Add To Playlist" is not working

### ISSUE THREAD

**Issue by orlea** [ndscor/SubMuxic#9]
When you select a track and choose "Add To Playlist" from the menu, a list of playlists will appear.
However, when I select the playlist I want to edit, it doesn't take me to the next screen, and the playlist will not be edited.

I checked the server logs and there's nothing in the logs.
It does work when using Dsub, so it doesn't appear to be a server issue.

- Android 10
- Sub Muxic VersionCode 24 VersionName '3.4'
- server : Navidrome v0.33.0

**Comment by caler1s** [comment]
I'm having the same issue. Nothing happens when tapping a playlist to add a track to, and nothing happens when tapping "Create new" either.

I also don't see any way to add the currently playing song to a playlist, is it supposed to be like that?

- Android 8
- Sub Muxic Version 3.4
- Server: Navidrome v0.33.0

**Comment by ndscor** [comment]
fixed in Version Name '3.5'
